// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnnouncementPost struct {
	PostID    int32            `json:"post_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

type Post struct {
	ID        int32            `json:"id"`
	AuthorID  int32            `json:"author_id"`
	Type      string           `json:"type"`
	Title     string           `json:"title"`
	Body      string           `json:"body"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Product struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Price     int32              `json:"price"`
	Quantity  int32              `json:"quantity"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Role  string `json:"role"`
}
